version: 1.0.{build}
environment:
  matrix:
    - nodejs_version: '14'
    - nodejs_version: '12'
    - nodejs_version: '10'
    - nodejs_version: '8'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
build_script:
  - cmd: >-
      npm install
      npm run build
test_script:
  - cmd: npm run unit
matrix:
  fast_finish: true
shallow_clone: true
notifications:
  - provider: GitHubPullRequest
    auth_token:
      secure: x3AJHtmTn5OT6J9/BBLYd4FQlVN0KAxR2gUDxo+iko5RJzF60IeF97SWpsbfJ02F
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
cache:
  - '%APPDATA%\npm-cache'
